// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechAcademyApi.Infrastructure.Persistence;

#nullable disable

namespace TechAcademyApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TechAcademyDbContext))]
    [Migration("20260407123900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TechAcademyApi.Core.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            CreatedDate = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "The Italian Kitchen"
                        },
                        new
                        {
                            Id = 2,
                            City = "San Francisco",
                            CreatedDate = new DateTime(2025, 2, 20, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Dragon Palace"
                        },
                        new
                        {
                            Id = 3,
                            City = "Boston",
                            CreatedDate = new DateTime(2025, 1, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Le Petit Bistro"
                        },
                        new
                        {
                            Id = 4,
                            City = "Seattle",
                            CreatedDate = new DateTime(2025, 3, 5, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Sakura Sushi House"
                        },
                        new
                        {
                            Id = 5,
                            City = "Austin",
                            CreatedDate = new DateTime(2025, 2, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "The Mexican Grill"
                        });
                });

            modelBuilder.Entity("TechAcademyApi.Core.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Excellent pasta and authentic Italian flavors! The ambiance is warm and inviting.",
                            CreatedDate = new DateTime(2025, 1, 20, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            RestaurantId = 1,
                            ReviewerName = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Great food, but a bit pricey. Service was attentive and quick.",
                            CreatedDate = new DateTime(2025, 1, 25, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            RestaurantId = 1,
                            ReviewerName = "Bob Smith"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Amazing dim sum! Fresh ingredients and perfect cooking. Must visit.",
                            CreatedDate = new DateTime(2025, 2, 22, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            RestaurantId = 2,
                            ReviewerName = "Charlie Brown"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Charming atmosphere and delicious food. French classics done right.",
                            CreatedDate = new DateTime(2025, 1, 12, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            RestaurantId = 3,
                            ReviewerName = "Diana Prince"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Best sushi in the city! Incredible quality and presentation. Highly recommend.",
                            CreatedDate = new DateTime(2025, 3, 8, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            RestaurantId = 4,
                            ReviewerName = "Emma Davis"
                        });
                });

            modelBuilder.Entity("TechAcademyApi.Core.Entities.Review", b =>
                {
                    b.HasOne("TechAcademyApi.Core.Entities.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TechAcademyApi.Core.Entities.Restaurant", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
